# Generated by Django 2.2.3 on 2019-07-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VegetarianStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(blank=True, max_length=100, null=True)),
                ('materials', models.ManyToManyField(to='materials.Material')),
            ],
            options={
                'db_table': 'vegetarian_stage',
            },
        ),
    ]
